### ISSUE TITLE
BUG- Cannot properly center table headers

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy-gui#560]
**Description**
In a table, if you want the headers to be centered for each column, they are not properly centered because the button for the arrow is always present in the calculation of the width, even if `editable=False` and `active=False`

**How to reproduce**
A code fragment  (`centertst.py`)
```python
import pandas as pd
from taipy import Gui
from taipy.gui import State

df = pd.DataFrame.from_records(
    [["ID1", 1, 2], ["ID2", 3, 4]], columns=["Wide", "A", "B"]
)

page = (
    "<|{df}|table|width=260px|show_all=True|editable=False|active=False"
    + "|width[A]=50px|width[B]=50px"
    + "|>"
)

if __name__ == "__main__":
    Gui(page=page, css_file="centertst").run(
        dark_mode=False,
    )
    
```
and CSS file `centertst.css`:
```css
.taipy-table :is(th, td) {
    border-width: 2px;
    border-color: lightgray;
    border-style: solid;
}

.taipy-table th {
    text-align: center !important;
    background-color: green;
}

.taipy-table td {
    text-align: center !important;
    background-color: lightblue;
}
```

**Expected behavior**
The centering should be aligned between the header and the contents of the columns.

**Screenshots**
![image](https://user-images.githubusercontent.com/15113894/210594471-f0d88bc5-456a-4ee4-bea5-9d4c76af33b8.png)

Using Chrome inspect, you can see how the button is still there, even though it is inactive:
![image](https://user-images.githubusercontent.com/15113894/210594892-1da70fb5-e92f-489f-95a3-3d45a58a476c.png)

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 10
 - Browser:  Chrome  108.0.5359.124 (Official Build) (64-bit)
 - taipy-gui:  2.0.4
